name: Run Athkar Bot 24/7

on:
  schedule:
    # Cron job to run the bot every hour
    - cron: "0 * * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Create requirements.txt if it doesn't exist
        if [ ! -f requirements.txt ]; then
          echo "discord.py>=2.0.0" > requirements.txt
          echo "python-dotenv" >> requirements.txt
          echo "flask" >> requirements.txt
        fi
        pip install -r requirements.txt

    - name: Run the bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: |
        echo "Starting the bot..."
        timeout 55m python main.py